### ISSUE TITLE
Consider support for Passive Event Listeners

### ISSUE THREAD

**Issue by jrstanley** [jeremenichelli/intersection-observer-polyfill#1]
[Passive Event Listeners](https://github.com/WICG/EventListenerOptions) can improve scroll performance, if we can guarantee that the scroll event listener will not call preventDefault().

Support currently exists in [Chrome 51+](https://www.chromestatus.com/features/5745543795965952) (and Opera 38+) and [FireFox 49+](https://bugzilla.mozilla.org/show_bug.cgi?id=1266066).

[Feature detection](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection) would be required for other browsers.

Is there merit in adding support for Passive Event Listeners?

**Comment by jeremenichelli** [comment]
Hi @jrstanley, I'm no longer developing this polyfill just because there's a much better one done by Das Surma from Google. I suggest taking a look at that version and leave comments and opinions in his PR, they will be well received for sure. Here's the link https://github.com/WICG/IntersectionObserver/pull/121
